/**
 * Auth Knowledge Base
 * Comprehensive data for all supported authentication providers
 */

import { AuthOption } from './types';

export const authProviders: AuthOption[] = [
  // Hosted Auth Providers
  {
    id: 'clerk',
    name: 'Clerk',
    category: 'auth',
    description: 'Complete user management with pre-built UI components',
    type: 'hosted',
    socialLogin: true,
    mfa: true,
    sso: true,
    prebuiltComponents: true,
    supportedRuntimes: ['node', 'bun'],
    pros: [
      'Beautiful pre-built components',
      'Excellent developer experience',
      'Easy social login setup',
      'Organizations & roles built-in',
      'Great documentation',
    ],
    cons: [
      'Can get expensive at scale',
      'Vendor lock-in',
      'Limited customization of UI',
    ],
    tradeoffs: [
      'Speed of implementation vs. cost at scale',
      'Pre-built UI vs. custom design needs',
      'Convenience vs. data ownership',
    ],
    bestFor: ['SaaS with teams', 'Rapid MVPs', 'Projects needing org features'],
    monthlyCost: { free: true, hobbyist: '$25', startup: '$99', enterprise: 'Custom' },
    requiredEnvVars: ['CLERK_SECRET_KEY', 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY'],
    compatibleWith: ['nextjs', 'tanstack-start', 'hono', 'express'],
    incompatibleWith: ['supabase-auth', 'firebase-auth', 'convex-auth'],
    complexity: 'low',
    logoEmoji: '🔐',
    documentationUrl: 'https://clerk.com/docs',
  },
  {
    id: 'kinde',
    name: 'Kinde',
    category: 'auth',
    description: 'B2B-focused authentication with feature flags',
    type: 'hosted',
    socialLogin: true,
    mfa: true,
    sso: true,
    prebuiltComponents: true,
    supportedRuntimes: ['node', 'bun'],
    pros: [
      'Feature flags included',
      'B2B focused (orgs, RBAC)',
      'Generous free tier',
      'Good Next.js integration',
    ],
    cons: [
      'Smaller community than Clerk/Auth0',
      'Fewer integrations',
      'UI less polished than Clerk',
    ],
    tradeoffs: [
      'Feature flags included vs. auth-only focus',
      'B2B features vs. B2C simplicity',
    ],
    bestFor: ['B2B SaaS', 'Apps needing feature flags', 'Cost-conscious teams'],
    monthlyCost: { free: true, hobbyist: '$25', startup: '$99', enterprise: 'Custom' },
    requiredEnvVars: ['KINDE_ISSUER_URL', 'KINDE_CLIENT_ID', 'KINDE_CLIENT_SECRET'],
    compatibleWith: ['nextjs', 'tanstack-start', 'hono'],
    incompatibleWith: ['supabase-auth', 'firebase-auth', 'convex-auth'],
    complexity: 'low',
    logoEmoji: '🦋',
    documentationUrl: 'https://docs.kinde.com',
  },
  {
    id: 'auth0',
    name: 'Auth0',
    category: 'auth',
    description: 'Enterprise-grade identity platform by Okta',
    type: 'hosted',
    socialLogin: true,
    mfa: true,
    sso: true,
    prebuiltComponents: true,
    supportedRuntimes: ['node', 'bun', 'python', 'go'],
    pros: [
      'Enterprise-grade security',
      'Extensive customization',
      'Wide language support',
      'Advanced features (Actions, Rules)',
    ],
    cons: [
      'Complex pricing',
      'Steep learning curve',
      'Can be overkill for simple apps',
    ],
    tradeoffs: [
      'Enterprise features vs. complexity',
      'Customization vs. simplicity',
    ],
    bestFor: ['Enterprise apps', 'Complex auth requirements', 'Multi-tenant apps'],
    monthlyCost: { free: true, hobbyist: '$23', startup: '$240', enterprise: 'Custom' },
    requiredEnvVars: ['AUTH0_SECRET', 'AUTH0_BASE_URL', 'AUTH0_ISSUER_BASE_URL', 'AUTH0_CLIENT_ID', 'AUTH0_CLIENT_SECRET'],
    compatibleWith: ['nextjs', 'express', 'hono', 'fastapi', 'gin-api'],
    incompatibleWith: ['supabase-auth', 'firebase-auth', 'convex-auth'],
    complexity: 'medium',
    logoEmoji: '🔒',
    documentationUrl: 'https://auth0.com/docs',
  },
  {
    id: 'workos',
    name: 'WorkOS',
    category: 'auth',
    description: 'Enterprise SSO and directory sync for B2B SaaS',
    type: 'hosted',
    socialLogin: false,
    mfa: true,
    sso: true,
    prebuiltComponents: false,
    supportedRuntimes: ['node', 'bun', 'python', 'go', 'rust'],
    pros: [
      'Best-in-class enterprise SSO',
      'Directory sync (SCIM)',
      'Pay-per-connection model',
      'Great for B2B enterprise sales',
    ],
    cons: [
      'No consumer auth features',
      'Expensive per SSO connection',
      'No pre-built UI',
    ],
    tradeoffs: [
      'Enterprise focus vs. consumer auth',
      'Per-connection pricing vs. flat rate',
    ],
    bestFor: ['Enterprise B2B SaaS', 'Apps selling to enterprises', 'SSO-first products'],
    monthlyCost: { free: true, hobbyist: null, startup: 'Pay-per-use', enterprise: 'Custom' },
    requiredEnvVars: ['WORKOS_API_KEY', 'WORKOS_CLIENT_ID'],
    compatibleWith: ['nextjs', 'express', 'hono', 'fastapi'],
    incompatibleWith: ['supabase-auth', 'firebase-auth'],
    complexity: 'medium',
    logoEmoji: '🏢',
    documentationUrl: 'https://workos.com/docs',
  },
  // Self-Hosted Auth
  {
    id: 'better-auth',
    name: 'Better Auth',
    category: 'auth',
    description: 'Modern, framework-agnostic authentication library',
    type: 'self-hosted',
    socialLogin: true,
    mfa: true,
    sso: false,
    prebuiltComponents: false,
    supportedRuntimes: ['node', 'bun'],
    pros: [
      'Full data ownership',
      'Modern TypeScript API',
      'Framework agnostic',
      'Active development',
    ],
    cons: [
      'Newer library (less battle-tested)',
      'No pre-built UI',
      'Requires database setup',
    ],
    tradeoffs: [
      'Control vs. hosted convenience',
      'Modern API vs. ecosystem maturity',
    ],
    bestFor: ['Data-sensitive apps', 'Custom auth flows', 'TypeScript projects'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['BETTER_AUTH_SECRET'],
    compatibleWith: ['nextjs', 'tanstack-start', 'hono', 'express', 'drizzle', 'prisma'],
    incompatibleWith: ['clerk', 'auth0', 'kinde'],
    complexity: 'medium',
    logoEmoji: '✨',
    documentationUrl: 'https://www.better-auth.com/docs',
  },
  {
    id: 'lucia',
    name: 'Lucia',
    category: 'auth',
    description: 'Simple, lightweight auth library with session management',
    type: 'self-hosted',
    socialLogin: true,
    mfa: false,
    sso: false,
    prebuiltComponents: false,
    supportedRuntimes: ['node', 'bun', 'deno'],
    pros: [
      'Very lightweight',
      'Minimal abstraction',
      'Good for learning auth',
      'Framework agnostic',
    ],
    cons: [
      'More manual setup',
      'Limited features',
      'Less active development',
    ],
    tradeoffs: [
      'Simplicity vs. features',
      'Learning vs. productivity',
    ],
    bestFor: ['Learning projects', 'Simple auth needs', 'Minimal overhead'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['nextjs', 'hono', 'express', 'drizzle', 'prisma'],
    incompatibleWith: ['clerk', 'auth0', 'kinde'],
    complexity: 'medium',
    logoEmoji: '🌙',
    documentationUrl: 'https://lucia-auth.com',
  },
  {
    id: 'authjs',
    name: 'Auth.js (NextAuth)',
    category: 'auth',
    description: 'Authentication for Next.js and other frameworks',
    type: 'self-hosted',
    socialLogin: true,
    mfa: false,
    sso: false,
    prebuiltComponents: false,
    supportedRuntimes: ['node', 'bun'],
    pros: [
      'Great Next.js integration',
      'Many OAuth providers',
      'Large community',
      'Flexible adapter system',
    ],
    cons: [
      'v5 migration issues',
      'Configuration can be complex',
      'Session handling quirks',
    ],
    tradeoffs: [
      'Ecosystem support vs. configuration complexity',
      'Flexibility vs. simplicity',
    ],
    bestFor: ['Next.js apps', 'OAuth-heavy apps', 'Existing NextAuth users'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['AUTH_SECRET'],
    compatibleWith: ['nextjs', 'drizzle', 'prisma'],
    incompatibleWith: ['clerk', 'auth0', 'kinde', 'hono'],
    complexity: 'medium',
    logoEmoji: '🔑',
    documentationUrl: 'https://authjs.dev',
  },
  // Platform-Specific Auth
  {
    id: 'supabase-auth',
    name: 'Supabase Auth',
    category: 'auth',
    description: 'Built-in authentication for Supabase projects',
    type: 'platform-specific',
    socialLogin: true,
    mfa: true,
    sso: false,
    prebuiltComponents: true,
    supportedRuntimes: ['node', 'bun', 'deno'],
    pros: [
      'Integrated with Supabase DB',
      'Row-level security integration',
      'No additional cost',
      'Easy setup',
    ],
    cons: [
      'Tied to Supabase',
      'Limited enterprise features',
      'UI components less polished',
    ],
    tradeoffs: [
      'Integration vs. independence',
      'Simplicity vs. enterprise features',
    ],
    bestFor: ['Supabase projects', 'Quick MVPs', 'Integrated stack needs'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['SUPABASE_URL', 'SUPABASE_ANON_KEY'],
    compatibleWith: ['supabase', 'nextjs', 'tanstack-start', 'hono'],
    incompatibleWith: ['clerk', 'auth0', 'kinde', 'firebase', 'convex'],
    complexity: 'low',
    logoEmoji: '⚡',
    documentationUrl: 'https://supabase.com/docs/guides/auth',
  },
  {
    id: 'firebase-auth',
    name: 'Firebase Auth',
    category: 'auth',
    description: 'Google authentication service for Firebase projects',
    type: 'platform-specific',
    socialLogin: true,
    mfa: true,
    sso: false,
    prebuiltComponents: true,
    supportedRuntimes: ['node', 'bun'],
    pros: [
      'Google ecosystem integration',
      'Phone auth built-in',
      'Anonymous auth support',
      'Generous free tier',
    ],
    cons: [
      'Google vendor lock-in',
      'Complex for non-Firebase projects',
      'Limited customization',
    ],
    tradeoffs: [
      'Google integration vs. independence',
      'Features vs. complexity for standalone use',
    ],
    bestFor: ['Firebase projects', 'Mobile apps', 'Google Cloud users'],
    monthlyCost: { free: true, hobbyist: null, startup: 'Pay-as-you-go', enterprise: null },
    requiredEnvVars: ['FIREBASE_PROJECT_ID', 'FIREBASE_API_KEY'],
    compatibleWith: ['firebase', 'nextjs'],
    incompatibleWith: ['clerk', 'auth0', 'supabase', 'convex'],
    complexity: 'medium',
    logoEmoji: '🔥',
    documentationUrl: 'https://firebase.google.com/docs/auth',
  },
  {
    id: 'convex-auth',
    name: 'Convex Auth',
    category: 'auth',
    description: 'Built-in authentication for Convex projects',
    type: 'platform-specific',
    socialLogin: true,
    mfa: false,
    sso: false,
    prebuiltComponents: false,
    supportedRuntimes: ['node', 'bun'],
    pros: [
      'Deep Convex integration',
      'Type-safe auth queries',
      'No additional setup',
    ],
    cons: [
      'Convex-only',
      'Fewer features than dedicated providers',
      'Newer solution',
    ],
    tradeoffs: [
      'Integration vs. features',
      'Simplicity vs. flexibility',
    ],
    bestFor: ['Convex projects', 'Reactive apps', 'Quick starts'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['CONVEX_DEPLOYMENT'],
    compatibleWith: ['convex', 'nextjs', 'tanstack-start'],
    incompatibleWith: ['clerk', 'auth0', 'supabase', 'firebase'],
    complexity: 'low',
    logoEmoji: '🔄',
    documentationUrl: 'https://docs.convex.dev/auth',
  },
  {
    id: 'pocketbase-auth',
    name: 'PocketBase Auth',
    category: 'auth',
    description: 'Built-in authentication for PocketBase',
    type: 'platform-specific',
    socialLogin: true,
    mfa: false,
    sso: false,
    prebuiltComponents: false,
    supportedRuntimes: ['node', 'bun', 'deno'],
    pros: [
      'Zero additional config',
      'OAuth providers supported',
      'Admin UI included',
    ],
    cons: [
      'PocketBase-only',
      'Limited enterprise features',
      'Single-instance limitation',
    ],
    tradeoffs: [
      'Simplicity vs. scale',
      'All-in-one vs. best-of-breed',
    ],
    bestFor: ['PocketBase projects', 'Side projects', 'Prototypes'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['POCKETBASE_URL'],
    compatibleWith: ['pocketbase', 'nextjs'],
    incompatibleWith: ['clerk', 'auth0', 'supabase', 'firebase', 'convex'],
    complexity: 'low',
    logoEmoji: '📦',
    documentationUrl: 'https://pocketbase.io/docs/authentication',
  },
  // None option
  {
    id: 'none',
    name: 'No Authentication',
    category: 'auth',
    description: 'Skip authentication setup',
    type: 'self-hosted',
    socialLogin: false,
    mfa: false,
    sso: false,
    prebuiltComponents: false,
    supportedRuntimes: ['node', 'bun', 'deno', 'python', 'go', 'rust'],
    pros: [
      'Simpler architecture',
      'No auth complexity',
      'Faster development',
    ],
    cons: [
      'No user management',
      'Public access only',
    ],
    tradeoffs: [
      'Simplicity vs. security',
    ],
    bestFor: ['Public APIs', 'Internal tools', 'Static sites'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: [],
    incompatibleWith: [],
    complexity: 'low',
    logoEmoji: '🚫',
  },
];

export const getAuthById = (id: string): AuthOption | undefined =>
  authProviders.find(auth => auth.id === id);

export const getAuthByType = (type: AuthOption['type']): AuthOption[] =>
  authProviders.filter(auth => auth.type === type);

export const getHostedAuthProviders = (): AuthOption[] =>
  authProviders.filter(auth => auth.type === 'hosted');

export const getSelfHostedAuthProviders = (): AuthOption[] =>
  authProviders.filter(auth => auth.type === 'self-hosted');
