/**
 * Database Knowledge Base
 * Comprehensive data for all supported database options
 */

import { DatabaseOption } from './types';

export const databases: DatabaseOption[] = [
  // Serverless PostgreSQL
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'database',
    description: 'PostgreSQL with built-in auth, storage, and realtime subscriptions',
    type: 'sql',
    hosting: 'baas',
    pros: [
      'Built-in auth, storage, and realtime',
      'Generous free tier (500MB, 2 projects)',
      'Auto-generated TypeScript types',
      'Dashboard UI for data management',
      'Row-level security built-in',
    ],
    cons: [
      'Vendor lock-in concerns',
      'Cold starts on free tier (~1-2s)',
      'Limited connection pooling on lower tiers',
      'Learning curve for RLS policies',
    ],
    tradeoffs: [
      'More features vs. more complexity',
      'Faster development vs. less flexibility',
      'Managed infrastructure vs. higher costs at scale',
    ],
    bestFor: ['SaaS applications', 'Startups needing quick MVP', 'Apps requiring realtime'],
    monthlyCost: { free: true, hobbyist: '$25', startup: '$75-200', enterprise: '$400+' },
    requiredEnvVars: ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY'],
    compatibleWith: ['drizzle', 'prisma', 'node', 'bun', 'deno', 'nextjs', 'hono'],
    incompatibleWith: [],
    complexity: 'low',
    scalability: 'high',
    supportedRuntimes: ['node', 'bun', 'deno', 'python'],
    connectionPooling: true,
    realtimeSupport: true,
    branchingSupport: false,
    logoEmoji: '⚡',
    documentationUrl: 'https://supabase.com/docs',
  },
  {
    id: 'neon',
    name: 'Neon',
    category: 'database',
    description: 'Serverless PostgreSQL with branching and scale-to-zero',
    type: 'sql',
    hosting: 'serverless',
    pros: [
      'Database branching for dev/preview',
      'Scale-to-zero reduces costs',
      'Fast cold starts (~500ms)',
      'Native Prisma integration',
      'Generous free tier',
    ],
    cons: [
      'Newer service (less battle-tested)',
      'Cold starts still exist',
      'No built-in auth/storage',
    ],
    tradeoffs: [
      'Developer experience vs. feature breadth',
      'Cost efficiency vs. always-on availability',
    ],
    bestFor: ['Preview environments', 'Cost-conscious teams', 'Prisma users'],
    monthlyCost: { free: true, hobbyist: '$19', startup: '$69-200', enterprise: 'Custom' },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['drizzle', 'prisma', 'kysely', 'node', 'bun', 'nextjs', 'hono'],
    incompatibleWith: [],
    complexity: 'low',
    scalability: 'high',
    supportedRuntimes: ['node', 'bun', 'deno', 'python', 'go', 'rust'],
    connectionPooling: true,
    realtimeSupport: false,
    branchingSupport: true,
    logoEmoji: '🐘',
    documentationUrl: 'https://neon.tech/docs',
  },
  {
    id: 'turso',
    name: 'Turso',
    category: 'database',
    description: 'Edge-first SQLite database with global replication',
    type: 'sql',
    hosting: 'serverless',
    pros: [
      'Extremely fast reads (edge locations)',
      'SQLite compatibility (embedded possible)',
      'Global replication built-in',
      'Very low latency',
    ],
    cons: [
      'SQLite limitations (no advanced Postgres features)',
      'Write performance less than read',
      'Smaller ecosystem than Postgres',
    ],
    tradeoffs: [
      'Speed vs. feature richness',
      'Simplicity vs. advanced SQL capabilities',
    ],
    bestFor: ['Edge applications', 'Read-heavy workloads', 'Global apps'],
    monthlyCost: { free: true, hobbyist: '$29', startup: '$79', enterprise: 'Custom' },
    requiredEnvVars: ['TURSO_DATABASE_URL', 'TURSO_AUTH_TOKEN'],
    compatibleWith: ['drizzle', 'node', 'bun', 'deno', 'hono', 'tanstack-start'],
    incompatibleWith: ['prisma'],
    complexity: 'low',
    scalability: 'high',
    supportedRuntimes: ['node', 'bun', 'deno', 'rust'],
    connectionPooling: false,
    realtimeSupport: false,
    branchingSupport: false,
    logoEmoji: '🚀',
    documentationUrl: 'https://docs.turso.tech',
  },
  {
    id: 'd1',
    name: 'Cloudflare D1',
    category: 'database',
    description: 'SQLite at the edge by Cloudflare',
    type: 'sql',
    hosting: 'serverless',
    pros: [
      'Tight Cloudflare Workers integration',
      'SQLite simplicity',
      'Global edge distribution',
      'Very generous free tier',
    ],
    cons: [
      'Cloudflare ecosystem lock-in',
      'Still in beta (maturing)',
      'Limited query features',
    ],
    tradeoffs: [
      'Edge speed vs. platform lock-in',
      'Simplicity vs. full SQL support',
    ],
    bestFor: ['Cloudflare Workers projects', 'Edge-first applications'],
    monthlyCost: { free: true, hobbyist: '$5', startup: '$25', enterprise: 'Custom' },
    requiredEnvVars: ['D1_DATABASE_ID'],
    compatibleWith: ['drizzle', 'node', 'hono'],
    incompatibleWith: ['prisma', 'express'],
    complexity: 'low',
    scalability: 'high',
    supportedRuntimes: ['node'],
    connectionPooling: false,
    realtimeSupport: false,
    branchingSupport: false,
    logoEmoji: '☁️',
    documentationUrl: 'https://developers.cloudflare.com/d1',
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    category: 'database',
    description: 'Embedded file-based SQL database',
    type: 'sql',
    hosting: 'self-hosted',
    pros: [
      'Zero configuration',
      'No server needed',
      'Extremely fast for small datasets',
      'Perfect for development',
    ],
    cons: [
      'Single-file concurrency limits',
      'No built-in replication',
      'Not suitable for high-traffic apps',
    ],
    tradeoffs: [
      'Simplicity vs. scalability',
      'Local speed vs. distributed access',
    ],
    bestFor: ['Development', 'Small applications', 'CLI tools', 'Embedded systems'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_PATH'],
    compatibleWith: ['drizzle', 'prisma', 'sqlalchemy', 'node', 'bun', 'python'],
    incompatibleWith: [],
    complexity: 'low',
    scalability: 'low',
    supportedRuntimes: ['node', 'bun', 'python', 'go', 'rust'],
    connectionPooling: false,
    realtimeSupport: false,
    branchingSupport: false,
    logoEmoji: '📁',
    documentationUrl: 'https://sqlite.org/docs.html',
  },
  // BaaS Options
  {
    id: 'convex',
    name: 'Convex',
    category: 'database',
    description: 'Reactive backend-as-a-service with real-time sync',
    type: 'document',
    hosting: 'baas',
    pros: [
      'Automatic real-time sync',
      'Type-safe queries',
      'Built-in scheduling and crons',
      'Great developer experience',
    ],
    cons: [
      'Strong vendor lock-in',
      'Learning curve for reactive model',
      'Less flexible than raw SQL',
    ],
    tradeoffs: [
      'Developer speed vs. flexibility',
      'Real-time features vs. SQL power',
    ],
    bestFor: ['Real-time apps', 'Collaborative tools', 'Rapid prototyping'],
    monthlyCost: { free: true, hobbyist: '$25', startup: '$100', enterprise: 'Custom' },
    requiredEnvVars: ['CONVEX_DEPLOYMENT', 'CONVEX_URL'],
    compatibleWith: ['node', 'bun', 'nextjs', 'tanstack-start'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'medium',
    scalability: 'high',
    supportedRuntimes: ['node', 'bun'],
    connectionPooling: false,
    realtimeSupport: true,
    branchingSupport: false,
    logoEmoji: '🔄',
    documentationUrl: 'https://docs.convex.dev',
  },
  {
    id: 'pocketbase',
    name: 'PocketBase',
    category: 'database',
    description: 'Open-source backend in a single file with SQLite',
    type: 'sql',
    hosting: 'self-hosted',
    pros: [
      'All-in-one (auth, DB, files)',
      'Single binary deployment',
      'Real-time subscriptions',
      'Admin UI included',
    ],
    cons: [
      'Single-instance only',
      'SQLite limitations apply',
      'Community-driven (not enterprise)',
    ],
    tradeoffs: [
      'Simplicity vs. scale',
      'Quick start vs. enterprise features',
    ],
    bestFor: ['Side projects', 'MVPs', 'Internal tools'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['POCKETBASE_URL'],
    compatibleWith: ['node', 'bun', 'nextjs'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'low',
    scalability: 'low',
    supportedRuntimes: ['node', 'bun', 'deno'],
    connectionPooling: false,
    realtimeSupport: true,
    branchingSupport: false,
    logoEmoji: '📦',
    documentationUrl: 'https://pocketbase.io/docs',
  },
  {
    id: 'firebase',
    name: 'Firebase Firestore',
    category: 'database',
    description: 'Google NoSQL document database with real-time sync',
    type: 'document',
    hosting: 'baas',
    pros: [
      'Excellent real-time capabilities',
      'Deep Google ecosystem integration',
      'Offline support built-in',
      'Generous free tier',
    ],
    cons: [
      'Complex pricing model',
      'Vendor lock-in to Google',
      'Limited query capabilities',
      'No joins',
    ],
    tradeoffs: [
      'Google ecosystem vs. independence',
      'Real-time power vs. query flexibility',
    ],
    bestFor: ['Mobile apps', 'Real-time apps', 'Google Cloud users'],
    monthlyCost: { free: true, hobbyist: '$25', startup: 'Pay-as-you-go', enterprise: 'Custom' },
    requiredEnvVars: ['FIREBASE_PROJECT_ID', 'FIREBASE_API_KEY'],
    compatibleWith: ['node', 'bun', 'nextjs'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'medium',
    scalability: 'unlimited',
    supportedRuntimes: ['node', 'bun', 'python'],
    connectionPooling: false,
    realtimeSupport: true,
    branchingSupport: false,
    logoEmoji: '🔥',
    documentationUrl: 'https://firebase.google.com/docs/firestore',
  },
  // Self-Hosted Options
  {
    id: 'postgres-local',
    name: 'PostgreSQL (Self-Hosted)',
    category: 'database',
    description: 'Self-hosted PostgreSQL via Docker',
    type: 'sql',
    hosting: 'self-hosted',
    pros: [
      'Full control over data',
      'No vendor lock-in',
      'All PostgreSQL features',
      'Predictable costs',
    ],
    cons: [
      'Requires DevOps knowledge',
      'Manual backups/scaling',
      'No automatic failover',
    ],
    tradeoffs: [
      'Control vs. convenience',
      'Cost savings vs. management overhead',
    ],
    bestFor: ['Teams with DevOps capacity', 'On-premise requirements', 'Cost optimization'],
    monthlyCost: { free: true, hobbyist: '$4-10 (VPS)', startup: '$20-100', enterprise: '$100+' },
    requiredEnvVars: ['DATABASE_URL', 'POSTGRES_PASSWORD'],
    compatibleWith: ['drizzle', 'prisma', 'sqlalchemy', 'gorm', 'sqlx-rust'],
    incompatibleWith: [],
    complexity: 'medium',
    scalability: 'medium',
    supportedRuntimes: ['node', 'bun', 'python', 'go', 'rust'],
    connectionPooling: true,
    realtimeSupport: false,
    branchingSupport: false,
    logoEmoji: '🐘',
    documentationUrl: 'https://www.postgresql.org/docs',
  },
  {
    id: 'mysql-local',
    name: 'MySQL (Self-Hosted)',
    category: 'database',
    description: 'Self-hosted MySQL via Docker',
    type: 'sql',
    hosting: 'self-hosted',
    pros: [
      'Widely supported',
      'Good performance',
      'Strong community',
      'Familiar to many developers',
    ],
    cons: [
      'Less feature-rich than Postgres',
      'Oracle ownership concerns',
      'Manual management required',
    ],
    tradeoffs: [
      'Familiarity vs. modern features',
      'Community size vs. innovation pace',
    ],
    bestFor: ['Legacy migrations', 'WordPress/PHP projects', 'MySQL expertise'],
    monthlyCost: { free: true, hobbyist: '$4-10', startup: '$20-100', enterprise: '$100+' },
    requiredEnvVars: ['DATABASE_URL', 'MYSQL_ROOT_PASSWORD'],
    compatibleWith: ['prisma', 'sqlalchemy', 'gorm'],
    incompatibleWith: ['drizzle'],
    complexity: 'medium',
    scalability: 'medium',
    supportedRuntimes: ['node', 'python', 'go', 'rust'],
    connectionPooling: true,
    realtimeSupport: false,
    branchingSupport: false,
    logoEmoji: '🐬',
    documentationUrl: 'https://dev.mysql.com/doc',
  },
  {
    id: 'mongodb-local',
    name: 'MongoDB (Self-Hosted)',
    category: 'database',
    description: 'Self-hosted document database via Docker',
    type: 'document',
    hosting: 'self-hosted',
    pros: [
      'Flexible schema',
      'Good for unstructured data',
      'Horizontal scaling possible',
      'JSON-native',
    ],
    cons: [
      'No ACID by default',
      'Memory-intensive',
      'Complex aggregations',
    ],
    tradeoffs: [
      'Schema flexibility vs. data integrity',
      'Document model vs. relational queries',
    ],
    bestFor: ['Unstructured data', 'Rapid iteration', 'Document-centric apps'],
    monthlyCost: { free: true, hobbyist: '$4-10', startup: '$20-100', enterprise: '$100+' },
    requiredEnvVars: ['MONGODB_URI'],
    compatibleWith: ['node', 'bun', 'python'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'medium',
    scalability: 'high',
    supportedRuntimes: ['node', 'bun', 'python', 'go', 'rust'],
    connectionPooling: true,
    realtimeSupport: false,
    branchingSupport: false,
    logoEmoji: '🍃',
    documentationUrl: 'https://docs.mongodb.com',
  },
  // Key-Value / Cache
  {
    id: 'redis',
    name: 'Redis',
    category: 'database',
    description: 'In-memory data structure store for caching and queues',
    type: 'key-value',
    hosting: 'self-hosted',
    pros: [
      'Extremely fast',
      'Versatile data structures',
      'Pub/Sub support',
      'Great for caching',
    ],
    cons: [
      'Memory-bound',
      'Persistence requires config',
      'Single-threaded core',
    ],
    tradeoffs: [
      'Speed vs. persistence guarantees',
      'Memory cost vs. performance',
    ],
    bestFor: ['Caching', 'Session storage', 'Real-time features', 'Job queues'],
    monthlyCost: { free: true, hobbyist: '$0-10', startup: '$25-100', enterprise: '$100+' },
    requiredEnvVars: ['REDIS_URL'],
    compatibleWith: ['node', 'bun', 'python', 'go', 'rust'],
    incompatibleWith: [],
    complexity: 'low',
    scalability: 'high',
    supportedRuntimes: ['node', 'bun', 'python', 'go', 'rust'],
    connectionPooling: true,
    realtimeSupport: true,
    branchingSupport: false,
    logoEmoji: '⚡',
    documentationUrl: 'https://redis.io/docs',
  },
  {
    id: 'upstash',
    name: 'Upstash Redis',
    category: 'database',
    description: 'Serverless Redis with per-request pricing',
    type: 'key-value',
    hosting: 'serverless',
    pros: [
      'Pay-per-request pricing',
      'Global replication',
      'REST API available',
      'No connection limits',
    ],
    cons: [
      'Latency higher than local Redis',
      'Costs can scale with traffic',
    ],
    tradeoffs: [
      'Serverless convenience vs. raw speed',
      'Cost efficiency at low scale vs. high scale',
    ],
    bestFor: ['Serverless functions', 'Edge deployments', 'Rate limiting'],
    monthlyCost: { free: true, hobbyist: '$10', startup: '$50', enterprise: 'Custom' },
    requiredEnvVars: ['UPSTASH_REDIS_REST_URL', 'UPSTASH_REDIS_REST_TOKEN'],
    compatibleWith: ['node', 'bun', 'deno', 'nextjs', 'hono'],
    incompatibleWith: [],
    complexity: 'low',
    scalability: 'unlimited',
    supportedRuntimes: ['node', 'bun', 'deno', 'python'],
    connectionPooling: false,
    realtimeSupport: false,
    branchingSupport: false,
    logoEmoji: '🔼',
    documentationUrl: 'https://docs.upstash.com',
  },
  // Enterprise Options
  {
    id: 'planetscale',
    name: 'PlanetScale',
    category: 'database',
    description: 'Serverless MySQL with Vitess-powered scaling',
    type: 'sql',
    hosting: 'serverless',
    pros: [
      'Non-blocking schema changes',
      'Database branching',
      'Horizontal scaling (Vitess)',
      'Great developer experience',
    ],
    cons: [
      'No foreign keys (Vitess limitation)',
      'MySQL only (not Postgres)',
      'Can get expensive at scale',
    ],
    tradeoffs: [
      'Scalability vs. relational features',
      'Developer experience vs. traditional SQL',
    ],
    bestFor: ['High-traffic apps', 'Teams needing safe migrations', 'MySQL preference'],
    monthlyCost: { free: true, hobbyist: '$29', startup: '$99', enterprise: 'Custom' },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['prisma', 'drizzle', 'node', 'bun'],
    incompatibleWith: [],
    complexity: 'medium',
    scalability: 'unlimited',
    supportedRuntimes: ['node', 'bun', 'python', 'go'],
    connectionPooling: true,
    realtimeSupport: false,
    branchingSupport: true,
    logoEmoji: '🪐',
    documentationUrl: 'https://docs.planetscale.com',
  },
  {
    id: 'cockroachdb',
    name: 'CockroachDB',
    category: 'database',
    description: 'Distributed SQL database for global apps',
    type: 'sql',
    hosting: 'managed',
    pros: [
      'Multi-region by default',
      'PostgreSQL compatible',
      'Automatic failover',
      'Strong consistency globally',
    ],
    cons: [
      'Complex for simple apps',
      'Higher latency than local',
      'Expensive at scale',
    ],
    tradeoffs: [
      'Global distribution vs. complexity',
      'Reliability vs. latency',
    ],
    bestFor: ['Global applications', 'High availability requirements', 'Financial apps'],
    monthlyCost: { free: true, hobbyist: '$0.50/vCPU-hr', startup: 'Custom', enterprise: 'Custom' },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['prisma', 'drizzle', 'node', 'go'],
    incompatibleWith: [],
    complexity: 'high',
    scalability: 'unlimited',
    supportedRuntimes: ['node', 'bun', 'python', 'go', 'rust'],
    connectionPooling: true,
    realtimeSupport: false,
    branchingSupport: false,
    logoEmoji: '🪳',
    documentationUrl: 'https://www.cockroachlabs.com/docs',
  },
  {
    id: 'valkey',
    name: 'Valkey',
    category: 'database',
    description: 'Open-source Redis fork with community governance',
    type: 'key-value',
    hosting: 'self-hosted',
    pros: [
      'Redis-compatible API',
      'Open-source governance',
      'No licensing concerns',
      'Active community development',
    ],
    cons: [
      'Newer project (less proven)',
      'Smaller ecosystem than Redis',
    ],
    tradeoffs: [
      'Open governance vs. Redis brand recognition',
      'Community-driven vs. company-backed',
    ],
    bestFor: ['Redis users concerned about licensing', 'Open-source advocates'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['VALKEY_URL'],
    compatibleWith: ['node', 'bun', 'python', 'go', 'rust'],
    incompatibleWith: [],
    complexity: 'low',
    scalability: 'high',
    supportedRuntimes: ['node', 'bun', 'python', 'go', 'rust'],
    connectionPooling: true,
    realtimeSupport: true,
    branchingSupport: false,
    logoEmoji: '🔑',
    documentationUrl: 'https://valkey.io/docs',
  },
  {
    id: 'dragonfly',
    name: 'Dragonfly',
    category: 'database',
    description: 'Modern Redis replacement with better performance',
    type: 'key-value',
    hosting: 'self-hosted',
    pros: [
      'Redis-compatible',
      '25x more memory efficient',
      'Multi-threaded',
      'Faster than Redis',
    ],
    cons: [
      'Newer project',
      'Some Redis features missing',
      'Smaller community',
    ],
    tradeoffs: [
      'Performance vs. ecosystem maturity',
      'Efficiency vs. feature parity',
    ],
    bestFor: ['High-performance caching', 'Memory-constrained environments'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: 'Custom' },
    requiredEnvVars: ['DRAGONFLY_URL'],
    compatibleWith: ['node', 'bun', 'python', 'go', 'rust'],
    incompatibleWith: [],
    complexity: 'low',
    scalability: 'high',
    supportedRuntimes: ['node', 'bun', 'python', 'go', 'rust'],
    connectionPooling: true,
    realtimeSupport: true,
    branchingSupport: false,
    logoEmoji: '🐉',
    documentationUrl: 'https://www.dragonflydb.io/docs',
  },
  // None option
  {
    id: 'none',
    name: 'No Database',
    category: 'database',
    description: 'Skip database setup (stateless application)',
    type: 'sql',
    hosting: 'self-hosted',
    pros: [
      'Simpler architecture',
      'No data management',
      'Faster development',
    ],
    cons: [
      'No persistent storage',
      'Limited functionality',
    ],
    tradeoffs: [
      'Simplicity vs. functionality',
    ],
    bestFor: ['Static sites', 'Serverless functions', 'API proxies'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: [],
    incompatibleWith: [],
    complexity: 'low',
    scalability: 'unlimited',
    supportedRuntimes: ['node', 'bun', 'deno', 'python', 'go', 'rust'],
    connectionPooling: false,
    realtimeSupport: false,
    branchingSupport: false,
    logoEmoji: '🚫',
  },
];

export const getDatabaseById = (id: string): DatabaseOption | undefined =>
  databases.find(db => db.id === id);

export const getDatabasesByType = (type: DatabaseOption['type']): DatabaseOption[] =>
  databases.filter(db => db.type === type);

export const getDatabasesByHosting = (hosting: DatabaseOption['hosting']): DatabaseOption[] =>
  databases.filter(db => db.hosting === hosting);
