/**
 * Frameworks Knowledge Base
 * Frontend and Backend framework options
 */

import { FrontendOption, BackendOption } from './types';

export const frontends: FrontendOption[] = [
  {
    id: 'nextjs',
    name: 'Next.js 15',
    category: 'frontend',
    description: 'React framework with App Router, RSC, and Server Actions',
    type: 'full-stack',
    ssr: true,
    ssg: true,
    serverComponents: true,
    typeSafe: true,
    bundler: 'Turbopack',
    pros: [
      'Industry standard for React',
      'Server Components reduce client JS',
      'Excellent SEO capabilities',
      'Vercel deployment optimized',
      'Large ecosystem and community',
    ],
    cons: [
      'Complex mental model (server vs client)',
      'Vercel-centric features',
      'Bundle size can grow quickly',
      'Learning curve for App Router',
    ],
    tradeoffs: [
      'Feature richness vs. complexity',
      'Vercel optimization vs. platform independence',
      'Server Components benefits vs. learning curve',
    ],
    bestFor: ['Production SaaS', 'SEO-critical apps', 'Full-stack React', 'Marketing sites'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['supabase', 'neon', 'clerk', 'prisma', 'drizzle', 'vercel-ai'],
    incompatibleWith: [],
    complexity: 'medium',
    logoEmoji: '▲',
    documentationUrl: 'https://nextjs.org/docs',
  },
  {
    id: 'tanstack-start',
    name: 'TanStack Start',
    category: 'frontend',
    description: 'Type-safe full-stack React framework with file-based routing',
    type: 'full-stack',
    ssr: true,
    ssg: true,
    serverComponents: false,
    typeSafe: true,
    bundler: 'Vite',
    pros: [
      'End-to-end type safety',
      'TanStack Query integration',
      'Vite-powered (fast HMR)',
      'Simpler mental model than Next.js',
    ],
    cons: [
      'Newer framework (less mature)',
      'Smaller ecosystem',
      'Less deployment platform support',
    ],
    tradeoffs: [
      'Type safety vs. ecosystem size',
      'Simplicity vs. feature breadth',
      'Modern DX vs. battle-tested stability',
    ],
    bestFor: ['Type-safe full-stack', 'TanStack users', 'Modern React apps'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['turso', 'better-auth', 'drizzle'],
    incompatibleWith: [],
    complexity: 'medium',
    logoEmoji: '🔷',
    documentationUrl: 'https://tanstack.com/start',
  },
  {
    id: 'vite-react',
    name: 'Vite + React',
    category: 'frontend',
    description: 'Lightning fast SPA setup with Vite and React',
    type: 'spa',
    ssr: false,
    ssg: false,
    serverComponents: false,
    typeSafe: true,
    bundler: 'Vite',
    pros: [
      'Extremely fast development',
      'Simple setup',
      'No server complexity',
      'Great for dashboards/apps',
    ],
    cons: [
      'No SSR (SEO limited)',
      'Client-side only',
      'Needs separate backend',
    ],
    tradeoffs: [
      'Simplicity vs. SEO/SSR',
      'Speed vs. full-stack features',
    ],
    bestFor: ['Admin dashboards', 'Internal tools', 'Apps behind auth', 'SPAs'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['hono', 'express', 'supabase', 'firebase'],
    incompatibleWith: [],
    complexity: 'low',
    logoEmoji: '⚡',
    documentationUrl: 'https://vitejs.dev',
  },
  {
    id: 'static',
    name: 'Static HTML/CSS/JS',
    category: 'frontend',
    description: 'Simple static site with no framework',
    type: 'static',
    ssr: false,
    ssg: true,
    serverComponents: false,
    typeSafe: false,
    bundler: 'None',
    pros: [
      'Maximum simplicity',
      'No build step required',
      'Fastest possible load times',
      'Deploy anywhere',
    ],
    cons: [
      'No component model',
      'Manual code organization',
      'Limited interactivity patterns',
    ],
    tradeoffs: [
      'Simplicity vs. scalability',
      'Performance vs. developer experience',
    ],
    bestFor: ['Landing pages', 'Simple sites', 'Documentation', 'Prototypes'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['nginx', 'caddy'],
    incompatibleWith: [],
    complexity: 'low',
    logoEmoji: '📄',
  },
];

export const backends: BackendOption[] = [
  // Node/Bun Backends
  {
    id: 'hono',
    name: 'Hono',
    category: 'backend',
    description: 'Ultra-fast, lightweight web framework for the edge',
    runtime: 'bun',
    type: 'minimal',
    edgeSupport: true,
    websocketSupport: true,
    openApiSupport: true,
    performanceRating: 'blazing',
    pros: [
      'Extremely lightweight (~14KB)',
      'Works everywhere (Node, Bun, Deno, Workers)',
      'Edge-first design',
      'Great TypeScript support',
      'Built-in middleware',
    ],
    cons: [
      'Smaller ecosystem than Express',
      'Less middleware available',
      'Newer framework',
    ],
    tradeoffs: [
      'Performance vs. ecosystem size',
      'Minimalism vs. batteries-included',
    ],
    bestFor: ['Edge APIs', 'Serverless', 'Microservices', 'High-performance APIs'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['drizzle', 'prisma', 'turso', 'd1', 'supabase', 'clerk'],
    incompatibleWith: [],
    complexity: 'low',
    logoEmoji: '🔥',
    documentationUrl: 'https://hono.dev',
  },
  {
    id: 'express',
    name: 'Express',
    category: 'backend',
    description: 'Minimal and flexible Node.js web framework',
    runtime: 'node',
    type: 'minimal',
    edgeSupport: false,
    websocketSupport: false,
    openApiSupport: false,
    performanceRating: 'fast',
    pros: [
      'Massive ecosystem',
      'Battle-tested (10+ years)',
      'Most tutorials/examples',
      'Huge middleware selection',
    ],
    cons: [
      'Not edge-compatible',
      'Slower than modern alternatives',
      'Callback-based (older patterns)',
      'No built-in TypeScript',
    ],
    tradeoffs: [
      'Ecosystem vs. performance',
      'Stability vs. modern features',
    ],
    bestFor: ['Traditional servers', 'Learning Node', 'Existing Express codebases'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['prisma', 'sequelize', 'mongodb-local', 'postgres-local'],
    incompatibleWith: ['d1', 'turso'],
    complexity: 'low',
    logoEmoji: '🚂',
    documentationUrl: 'https://expressjs.com',
  },
  {
    id: 'elysia',
    name: 'Elysia',
    category: 'backend',
    description: 'Bun-native framework with end-to-end type safety',
    runtime: 'bun',
    type: 'batteries-included',
    edgeSupport: false,
    websocketSupport: true,
    openApiSupport: true,
    performanceRating: 'blazing',
    pros: [
      'Fastest Bun framework',
      'End-to-end type safety (Eden)',
      'Built-in validation',
      'Great developer experience',
    ],
    cons: [
      'Bun-only (no Node support)',
      'Smaller community',
      'Less deployment platform support',
    ],
    tradeoffs: [
      'Performance vs. platform support',
      'Type safety vs. ecosystem',
    ],
    bestFor: ['Bun projects', 'Type-safe APIs', 'High-performance backends'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['drizzle', 'prisma', 'supabase'],
    incompatibleWith: ['d1'],
    complexity: 'low',
    logoEmoji: '🦊',
    documentationUrl: 'https://elysiajs.com',
  },
  // Deno Backend
  {
    id: 'fresh',
    name: 'Fresh',
    category: 'backend',
    description: 'Deno web framework with islands architecture',
    runtime: 'deno',
    type: 'batteries-included',
    edgeSupport: true,
    websocketSupport: true,
    openApiSupport: false,
    performanceRating: 'very-fast',
    pros: [
      'Zero config',
      'Islands architecture (minimal JS)',
      'Deno Deploy integration',
      'TypeScript by default',
    ],
    cons: [
      'Deno-only ecosystem',
      'Smaller community',
      'Less npm compatibility',
    ],
    tradeoffs: [
      'Modern architecture vs. ecosystem size',
      'Security vs. compatibility',
    ],
    bestFor: ['Deno projects', 'Edge-first apps', 'Minimal client JS needs'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['supabase', 'turso'],
    incompatibleWith: ['prisma'],
    complexity: 'medium',
    logoEmoji: '🍋',
    documentationUrl: 'https://fresh.deno.dev',
  },
  // Python Backends
  {
    id: 'fastapi',
    name: 'FastAPI',
    category: 'backend',
    description: 'Modern, fast Python framework with automatic API docs',
    runtime: 'python',
    type: 'batteries-included',
    edgeSupport: false,
    websocketSupport: true,
    openApiSupport: true,
    performanceRating: 'very-fast',
    pros: [
      'Automatic OpenAPI docs',
      'Type hints for validation',
      'Async support',
      'Great for ML/AI backends',
    ],
    cons: [
      'Python GIL limitations',
      'Less performant than Go/Rust',
      'Async can be complex',
    ],
    tradeoffs: [
      'Developer experience vs. raw performance',
      'Python ecosystem vs. language limitations',
    ],
    bestFor: ['ML/AI APIs', 'Data science backends', 'Rapid Python development'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['sqlalchemy', 'sqlmodel', 'tortoise', 'postgres-local'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'low',
    logoEmoji: '⚡',
    documentationUrl: 'https://fastapi.tiangolo.com',
  },
  {
    id: 'litestar',
    name: 'Litestar',
    category: 'backend',
    description: 'High-performance Python ASGI framework',
    runtime: 'python',
    type: 'batteries-included',
    edgeSupport: false,
    websocketSupport: true,
    openApiSupport: true,
    performanceRating: 'very-fast',
    pros: [
      'Faster than FastAPI',
      'Built-in dependency injection',
      'Better OpenAPI integration',
      'More batteries included',
    ],
    cons: [
      'Smaller community than FastAPI',
      'Less tutorials available',
      'Newer project',
    ],
    tradeoffs: [
      'Performance vs. community size',
      'Features vs. learning resources',
    ],
    bestFor: ['High-performance Python APIs', 'Enterprise Python', 'Complex APIs'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['sqlalchemy', 'tortoise', 'postgres-local'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'medium',
    logoEmoji: '⭐',
    documentationUrl: 'https://litestar.dev',
  },
  // Go Backends
  {
    id: 'gin',
    name: 'Gin',
    category: 'backend',
    description: 'Fast HTTP web framework for Go',
    runtime: 'go',
    type: 'minimal',
    edgeSupport: false,
    websocketSupport: false,
    openApiSupport: false,
    performanceRating: 'blazing',
    pros: [
      'Very fast',
      'Most popular Go framework',
      'Simple and intuitive',
      'Good middleware ecosystem',
    ],
    cons: [
      'Less batteries-included',
      'Manual validation setup',
      'No built-in ORM',
    ],
    tradeoffs: [
      'Performance vs. features',
      'Simplicity vs. boilerplate',
    ],
    bestFor: ['High-performance Go APIs', 'Microservices', 'Go teams'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['gorm', 'sqlx-go', 'postgres-local'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'low',
    logoEmoji: '🍸',
    documentationUrl: 'https://gin-gonic.com/docs',
  },
  {
    id: 'fiber',
    name: 'Fiber',
    category: 'backend',
    description: 'Express-inspired Go web framework',
    runtime: 'go',
    type: 'minimal',
    edgeSupport: false,
    websocketSupport: true,
    openApiSupport: false,
    performanceRating: 'blazing',
    pros: [
      'Express-like API',
      'Very fast (fasthttp)',
      'Easy for Node developers',
      'Good WebSocket support',
    ],
    cons: [
      'Non-standard HTTP (fasthttp)',
      'Some incompatibilities',
      'Smaller than Gin',
    ],
    tradeoffs: [
      'Familiarity vs. Go idioms',
      'Performance vs. compatibility',
    ],
    bestFor: ['Node devs learning Go', 'WebSocket apps', 'High-performance APIs'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['gorm', 'sqlx-go', 'postgres-local'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'low',
    logoEmoji: '🚀',
    documentationUrl: 'https://docs.gofiber.io',
  },
  {
    id: 'echo',
    name: 'Echo',
    category: 'backend',
    description: 'High performance, minimalist Go web framework',
    runtime: 'go',
    type: 'minimal',
    edgeSupport: false,
    websocketSupport: true,
    openApiSupport: false,
    performanceRating: 'blazing',
    pros: [
      'Minimalist design',
      'Standard library compatible',
      'Good documentation',
      'Middleware system',
    ],
    cons: [
      'Smaller ecosystem than Gin',
      'Less community content',
    ],
    tradeoffs: [
      'Minimalism vs. features',
      'Standard library vs. abstractions',
    ],
    bestFor: ['Minimalist Go APIs', 'Standard library enthusiasts'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['gorm', 'sqlx-go', 'postgres-local'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'low',
    logoEmoji: '📢',
    documentationUrl: 'https://echo.labstack.com',
  },
  // Rust Backends
  {
    id: 'axum',
    name: 'Axum',
    category: 'backend',
    description: 'Ergonomic and modular web framework for Rust',
    runtime: 'rust',
    type: 'minimal',
    edgeSupport: false,
    websocketSupport: true,
    openApiSupport: false,
    performanceRating: 'blazing',
    pros: [
      'Tokio ecosystem integration',
      'Type-safe extractors',
      'Tower middleware compatible',
      'Excellent performance',
    ],
    cons: [
      'Steep Rust learning curve',
      'Compile times',
      'Smaller web ecosystem',
    ],
    tradeoffs: [
      'Safety vs. development speed',
      'Performance vs. ecosystem',
    ],
    bestFor: ['High-performance Rust APIs', 'Type safety maximalists', 'Async Rust'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['sqlx-rust', 'sea-orm', 'postgres-local'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'high',
    logoEmoji: '🦀',
    documentationUrl: 'https://docs.rs/axum',
  },
  {
    id: 'actix',
    name: 'Actix Web',
    category: 'backend',
    description: 'Powerful, pragmatic Rust web framework',
    runtime: 'rust',
    type: 'batteries-included',
    edgeSupport: false,
    websocketSupport: true,
    openApiSupport: false,
    performanceRating: 'blazing',
    pros: [
      'One of fastest frameworks',
      'Actor model support',
      'Mature ecosystem',
      'Great for high-traffic',
    ],
    cons: [
      'Complex actor model',
      'Steep learning curve',
      'Heavy for simple APIs',
    ],
    tradeoffs: [
      'Performance vs. simplicity',
      'Features vs. learning curve',
    ],
    bestFor: ['Maximum performance Rust APIs', 'High-traffic services', 'Actor-based systems'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: [],
    compatibleWith: ['sqlx-rust', 'sea-orm', 'diesel', 'postgres-local'],
    incompatibleWith: ['prisma', 'drizzle'],
    complexity: 'high',
    logoEmoji: '🎭',
    documentationUrl: 'https://actix.rs/docs',
  },
];

export const getFrontendById = (id: string): FrontendOption | undefined =>
  frontends.find(f => f.id === id);

export const getBackendById = (id: string): BackendOption | undefined =>
  backends.find(b => b.id === id);

export const getBackendsByRuntime = (runtime: string): BackendOption[] =>
  backends.filter(b => b.runtime === runtime);

export const getEdgeCompatibleBackends = (): BackendOption[] =>
  backends.filter(b => b.edgeSupport);
