/**
 * ORM Knowledge Base
 * Comprehensive data for all supported ORM options
 */

import { ORMOption } from './types';

export const orms: ORMOption[] = [
  // JavaScript/TypeScript ORMs
  {
    id: 'drizzle',
    name: 'Drizzle ORM',
    category: 'orm',
    description: 'Type-safe SQL-like ORM with excellent performance',
    supportedDatabases: ['postgres', 'mysql', 'sqlite', 'supabase', 'neon', 'turso', 'd1'],
    typeSafety: true,
    migrations: true,
    queryStyle: 'sql-like',
    supportedRuntimes: ['node', 'bun', 'deno'],
    pros: [
      'SQL-like syntax feels natural',
      'Excellent TypeScript support',
      'Lightweight (~35KB bundle)',
      'Edge-ready (works with D1, Turso)',
      'Schema-as-code approach',
    ],
    cons: [
      'Newer ecosystem (less content/plugins)',
      'Less magic (more explicit code)',
      'Fewer integrations than Prisma',
    ],
    tradeoffs: [
      'Control vs. convenience',
      'Performance vs. abstraction',
      'Learning SQL vs. higher-level APIs',
    ],
    bestFor: ['Edge deployments', 'Performance-critical apps', 'SQL enthusiasts', 'Serverless'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['supabase', 'neon', 'turso', 'd1', 'postgres-local', 'sqlite', 'hono', 'nextjs'],
    incompatibleWith: ['mongodb-local', 'firebase', 'convex'],
    complexity: 'medium',
    logoEmoji: '💧',
    documentationUrl: 'https://orm.drizzle.team/docs/overview',
  },
  {
    id: 'prisma',
    name: 'Prisma',
    category: 'orm',
    description: 'Schema-first ORM with great developer experience',
    supportedDatabases: ['postgres', 'mysql', 'sqlite', 'mongodb', 'sqlserver', 'cockroachdb'],
    typeSafety: true,
    migrations: true,
    queryStyle: 'schema-first',
    supportedRuntimes: ['node', 'bun'],
    pros: [
      'Excellent developer experience',
      'Prisma Studio UI',
      'Auto-generated types',
      'Great documentation',
      'Large community',
    ],
    cons: [
      'Larger bundle size (~2MB)',
      'Cold start impact on serverless',
      'Schema file required',
      'Query limitations for complex SQL',
    ],
    tradeoffs: [
      'Developer experience vs. bundle size',
      'Abstraction vs. raw SQL control',
      'Ecosystem size vs. edge compatibility',
    ],
    bestFor: ['Rapid development', 'Teams prioritizing DX', 'Traditional server deployments'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['supabase', 'neon', 'postgres-local', 'mysql-local', 'planetscale', 'cockroachdb'],
    incompatibleWith: ['turso', 'd1', 'firebase', 'convex', 'pocketbase'],
    complexity: 'low',
    logoEmoji: '▲',
    documentationUrl: 'https://www.prisma.io/docs',
  },
  {
    id: 'kysely',
    name: 'Kysely',
    category: 'orm',
    description: 'Type-safe SQL query builder for TypeScript',
    supportedDatabases: ['postgres', 'mysql', 'sqlite'],
    typeSafety: true,
    migrations: true,
    queryStyle: 'query-builder',
    supportedRuntimes: ['node', 'bun', 'deno'],
    pros: [
      'Pure TypeScript (no code generation)',
      'Full SQL control',
      'Lightweight',
      'Great for complex queries',
    ],
    cons: [
      'More verbose than Prisma',
      'Smaller community',
      'Manual migrations',
    ],
    tradeoffs: [
      'SQL control vs. higher-level abstraction',
      'Type safety vs. simplicity',
    ],
    bestFor: ['Complex SQL queries', 'TypeScript purists', 'Custom SQL needs'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['postgres-local', 'mysql-local', 'sqlite', 'neon', 'planetscale'],
    incompatibleWith: ['turso', 'd1', 'firebase', 'convex'],
    complexity: 'medium',
    logoEmoji: '🔷',
    documentationUrl: 'https://kysely.dev/docs/intro',
  },
  // Python ORMs
  {
    id: 'sqlalchemy',
    name: 'SQLAlchemy',
    category: 'orm',
    description: 'Python SQL toolkit and ORM with maximum flexibility',
    supportedDatabases: ['postgres', 'mysql', 'sqlite', 'sqlserver', 'oracle'],
    typeSafety: false,
    migrations: true,
    queryStyle: 'object-oriented',
    supportedRuntimes: ['python'],
    pros: [
      'Extremely mature and battle-tested',
      'Flexible (Core vs ORM)',
      'Async support (2.0+)',
      'Extensive documentation',
    ],
    cons: [
      'Steep learning curve',
      'Complex for simple use cases',
      'Verbose syntax',
    ],
    tradeoffs: [
      'Flexibility vs. simplicity',
      'Power vs. learning curve',
    ],
    bestFor: ['Complex Python backends', 'Enterprise applications', 'Database experts'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['postgres-local', 'mysql-local', 'sqlite', 'fastapi', 'litestar'],
    incompatibleWith: ['firebase', 'convex', 'pocketbase'],
    complexity: 'high',
    logoEmoji: '🐍',
    documentationUrl: 'https://docs.sqlalchemy.org',
  },
  {
    id: 'sqlmodel',
    name: 'SQLModel',
    category: 'orm',
    description: 'SQL databases in Python designed for simplicity and FastAPI',
    supportedDatabases: ['postgres', 'mysql', 'sqlite'],
    typeSafety: true,
    migrations: false,
    queryStyle: 'object-oriented',
    supportedRuntimes: ['python'],
    pros: [
      'Built by FastAPI creator',
      'Pydantic integration',
      'Simple and intuitive',
      'Great for FastAPI projects',
    ],
    cons: [
      'Fewer features than SQLAlchemy',
      'Less mature',
      'No built-in migrations',
    ],
    tradeoffs: [
      'Simplicity vs. features',
      'FastAPI integration vs. framework independence',
    ],
    bestFor: ['FastAPI projects', 'Simple CRUD apps', 'Python beginners'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['postgres-local', 'mysql-local', 'sqlite', 'fastapi'],
    incompatibleWith: ['firebase', 'convex'],
    complexity: 'low',
    logoEmoji: '📊',
    documentationUrl: 'https://sqlmodel.tiangolo.com',
  },
  {
    id: 'tortoise',
    name: 'Tortoise ORM',
    category: 'orm',
    description: 'Async-first ORM inspired by Django',
    supportedDatabases: ['postgres', 'mysql', 'sqlite'],
    typeSafety: false,
    migrations: true,
    queryStyle: 'object-oriented',
    supportedRuntimes: ['python'],
    pros: [
      'Django-like syntax',
      'Async-native',
      'Built-in migrations (Aerich)',
      'Good documentation',
    ],
    cons: [
      'Smaller community than SQLAlchemy',
      'Less flexible',
      'Fewer database backends',
    ],
    tradeoffs: [
      'Async-first vs. sync compatibility',
      'Simplicity vs. SQLAlchemy power',
    ],
    bestFor: ['Async Python apps', 'Django developers moving to async', 'FastAPI projects'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['postgres-local', 'mysql-local', 'sqlite', 'fastapi', 'litestar'],
    incompatibleWith: ['firebase', 'convex'],
    complexity: 'medium',
    logoEmoji: '🐢',
    documentationUrl: 'https://tortoise.github.io',
  },
  // Go ORMs
  {
    id: 'gorm',
    name: 'GORM',
    category: 'orm',
    description: 'The fantastic ORM library for Go',
    supportedDatabases: ['postgres', 'mysql', 'sqlite', 'sqlserver'],
    typeSafety: false,
    migrations: true,
    queryStyle: 'object-oriented',
    supportedRuntimes: ['go'],
    pros: [
      'Most popular Go ORM',
      'Auto migrations',
      'Association handling',
      'Hooks system',
    ],
    cons: [
      'Performance overhead vs raw SQL',
      'Magic can be confusing',
      'Complex query limitations',
    ],
    tradeoffs: [
      'Convenience vs. performance',
      'Magic vs. explicit code',
    ],
    bestFor: ['Go web apps', 'Rapid Go development', 'CRUD-heavy applications'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['postgres-local', 'mysql-local', 'sqlite', 'gin-api', 'fiber-api', 'echo-api'],
    incompatibleWith: ['firebase', 'convex'],
    complexity: 'medium',
    logoEmoji: '🔵',
    documentationUrl: 'https://gorm.io/docs',
  },
  {
    id: 'sqlx-go',
    name: 'sqlx (Go)',
    category: 'orm',
    description: 'Extensions to Go standard library database/sql',
    supportedDatabases: ['postgres', 'mysql', 'sqlite'],
    typeSafety: false,
    migrations: false,
    queryStyle: 'sql-like',
    supportedRuntimes: ['go'],
    pros: [
      'Minimal abstraction',
      'Close to database/sql',
      'Good performance',
      'Simple and predictable',
    ],
    cons: [
      'More boilerplate',
      'No migrations included',
      'Manual struct mapping',
    ],
    tradeoffs: [
      'Control vs. convenience',
      'Performance vs. features',
    ],
    bestFor: ['Performance-critical Go apps', 'SQL experts', 'Minimal abstraction needs'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['postgres-local', 'mysql-local', 'sqlite', 'gin-api', 'fiber-api'],
    incompatibleWith: ['firebase', 'convex'],
    complexity: 'low',
    logoEmoji: '📦',
    documentationUrl: 'https://jmoiron.github.io/sqlx',
  },
  // Rust ORMs
  {
    id: 'sqlx-rust',
    name: 'SQLx (Rust)',
    category: 'orm',
    description: 'Async, compile-time checked SQL queries for Rust',
    supportedDatabases: ['postgres', 'mysql', 'sqlite'],
    typeSafety: true,
    migrations: true,
    queryStyle: 'sql-like',
    supportedRuntimes: ['rust'],
    pros: [
      'Compile-time SQL checking',
      'Async-first',
      'Zero-cost abstractions',
      'No DSL to learn',
    ],
    cons: [
      'Compile times increase',
      'Database needed for compile-time checks',
      'Less abstraction than ORMs',
    ],
    tradeoffs: [
      'Type safety vs. compile time',
      'Raw SQL control vs. ORM convenience',
    ],
    bestFor: ['Rust backends', 'Type safety enthusiasts', 'Performance-critical apps'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['postgres-local', 'mysql-local', 'sqlite', 'axum-api', 'actix-api'],
    incompatibleWith: ['firebase', 'convex'],
    complexity: 'medium',
    logoEmoji: '🦀',
    documentationUrl: 'https://github.com/launchbadge/sqlx',
  },
  {
    id: 'sea-orm',
    name: 'SeaORM',
    category: 'orm',
    description: 'Async & dynamic ORM for Rust',
    supportedDatabases: ['postgres', 'mysql', 'sqlite'],
    typeSafety: true,
    migrations: true,
    queryStyle: 'object-oriented',
    supportedRuntimes: ['rust'],
    pros: [
      'Full-featured ORM',
      'Active Record pattern',
      'Good documentation',
      'Built on SQLx',
    ],
    cons: [
      'More dependencies',
      'Slower compile times',
      'Less mature than SQLx',
    ],
    tradeoffs: [
      'ORM features vs. compilation speed',
      'Abstraction vs. raw SQL control',
    ],
    bestFor: ['Rust web apps', 'Teams wanting traditional ORM', 'Complex domain models'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['postgres-local', 'mysql-local', 'sqlite', 'axum-api', 'actix-api'],
    incompatibleWith: ['firebase', 'convex'],
    complexity: 'medium',
    logoEmoji: '🌊',
    documentationUrl: 'https://www.sea-ql.org/SeaORM',
  },
  {
    id: 'diesel',
    name: 'Diesel',
    category: 'orm',
    description: 'Safe, extensible ORM and query builder for Rust',
    supportedDatabases: ['postgres', 'mysql', 'sqlite'],
    typeSafety: true,
    migrations: true,
    queryStyle: 'query-builder',
    supportedRuntimes: ['rust'],
    pros: [
      'Compile-time guarantees',
      'Zero-cost abstractions',
      'Mature ecosystem',
      'Strong type safety',
    ],
    cons: [
      'Sync-only (no async)',
      'Steep learning curve',
      'Complex macro system',
    ],
    tradeoffs: [
      'Type safety vs. async support',
      'Compile-time checks vs. flexibility',
    ],
    bestFor: ['Sync Rust apps', 'Type safety maximalists', 'CLI applications'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: ['postgres-local', 'mysql-local', 'sqlite', 'actix-api'],
    incompatibleWith: ['firebase', 'convex', 'axum-api'],
    complexity: 'high',
    logoEmoji: '⛽',
    documentationUrl: 'https://diesel.rs/guides',
  },
  // None option
  {
    id: 'none',
    name: 'No ORM (Raw SQL)',
    category: 'orm',
    description: 'Use raw SQL queries without an ORM',
    supportedDatabases: ['postgres', 'mysql', 'sqlite'],
    typeSafety: false,
    migrations: false,
    queryStyle: 'sql-like',
    supportedRuntimes: ['node', 'bun', 'deno', 'python', 'go', 'rust'],
    pros: [
      'Maximum control',
      'Best performance',
      'No abstraction overhead',
      'Full SQL features',
    ],
    cons: [
      'More boilerplate',
      'SQL injection risk if not careful',
      'No type safety by default',
    ],
    tradeoffs: [
      'Control vs. convenience',
      'Performance vs. developer speed',
    ],
    bestFor: ['Simple queries', 'Performance-critical paths', 'SQL experts'],
    monthlyCost: { free: true, hobbyist: null, startup: null, enterprise: null },
    requiredEnvVars: ['DATABASE_URL'],
    compatibleWith: [],
    incompatibleWith: [],
    complexity: 'low',
    logoEmoji: '📝',
  },
];

export const getORMById = (id: string): ORMOption | undefined =>
  orms.find(orm => orm.id === id);

export const getORMsByRuntime = (runtime: string): ORMOption[] =>
  orms.filter(orm => orm.supportedRuntimes.includes(runtime as any));

export const getORMsByDatabase = (database: string): ORMOption[] =>
  orms.filter(orm => orm.supportedDatabases.includes(database));
